=== myblindy/raid-leader-management/rlm/Data/Schemas/mechanics_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for raid mechanics",

  "type": "object",

  "definitions": {
    "role": {
      "type": "string",
      "enum": [ "tank", "meleeDamage", "rangedDamage", "healer" ]
    }
  },

  "properties": {
    "name": {
      "type": "string"
    },
    "difficulty": {
      "type": "number",
      "minimum": 0,
      "description": "Percentage at base difficulty (at same ilvl as the fight is designed for)."
    },
    "rate": {
      "type": "string",
      "enum": [ "veryRare", "rare", "normal", "often", "veryOften" ]
    },
    "targetRoles": {
      "type": "array",
      "items": { "$ref": "#/definitions/role" }
    },
    "targetCount": {
      "type": "string",
      "enum": [ "one", "all", "few", "many" ]
    },
    "failureCheckRoles": {
      "type": "array",
      "items": { "$ref": "#/definitions/role" }
    },
    "failureCheckAffectedTargets": {
      "type": "boolean"
    },
    "failureType": {
      "type": "string",
      "enum": [ "death", "difficultyIncrease" ]
    },
    "failureDifficultyIncrease": {
      "type": "number",
      "minimum": 0,
      "description": "Percentage at base difficulty (at same ilvl as the fight is designed for)."
    }
  },

  "required": [ "name", "difficulty", "failureType", "rate", "targetRoles", "targetCount" ]
}

=== myblindy/raid-leader-management/rlm/Data/Mechanics/ability_cost_curse.json
{
  "$schema": "../schemas/mechanics_schema.json",
  "name": "Ability Cost Curse",
  "difficulty": 40,
  "rate": "often",
  "targetRoles": [ "meleeDamage", "rangedDamage", "healer" ],
  "targetCount": "few",
  "failureCheckRoles": [ "healer" ],
  "failureType": "difficultyIncrease",
  "failureDifficultyIncrease": 2
}

=== myblindy/raid-leader-management/rlm/Data/Mechanics/fear.json
{
  "$schema": "../schemas/mechanics_schema.json",
  "name": "Fear",
  "difficulty": 60,
  "rate": "often",
  "targetRoles": [ "rangedDamage", "meleeDamage", "healer" ],
  "targetCount": "one",
  "failureCheckAffectedTargets": true,
  "failureType": "difficultyIncrease",
  "failureDifficultyIncrease": 4
}
